redis:
  host: "localhost"
  port: 6379
  db: 0

serial:
  port_name: "COM26"
  baud_rate: 9600
  timeout: 0.2

bluetooth:
  adress: "F0:F5:64:8C:CB:07"
  char_uuid: "00001101-0000-1000-8000-00805f9b34fb"

sim:
  tick_rate: 60
  start_position:
    x: 500
    y: 400
    direction: 0
  window:
    width: 1300
    height: 700

movement_coeff:
  forward: 0.38
  translate: 1.0
  rotate: 1.105

inertie_factor:
  forward: 0.0 #0.9
  translate: 0.0 # 0.9
  rotate: 0.0 # 0.4

utils:
  logger:
    log_freq: 0.5

others:
  prev_pos_buffer_len: 100